// Generated by CoffeeScript 1.9.1
var flashFunc, flashInterval, flashText, flashToggle, stateToggle;

flashText = d3.select("body").select("span#flash");

flashToggle = 0;

stateToggle = 1;

flashFunc = function() {
  flashText.attr("class", function() {
    if (flashToggle === 5) {
      flashToggle = -1;
      return "highlight";
    }
    return "glow";
  });
  return flashToggle++;
};

flashInterval = setInterval(flashFunc, 0);

clearInterval(flashInterval);

flashText.on("click", function() {
  if (stateToggle === 0) {
    clearInterval(flashInterval);
    d3.select(this).attr("class", "highlight");
  } else if (stateToggle === 1) {
    d3.select(this).attr("class", "glow");
  } else {
    d3.select(this).attr("class", "highlight");
    flashToggle = 0;
    flashInterval = setInterval(flashFunc, 400);
  }
  stateToggle++;
  if (stateToggle > 2) {
    return stateToggle = 0;
  }
});
