// Generated by CoffeeScript 2.4.1
// Scatterplot example
// uses plotframe.coffee
var scatterplot, stop_scatterplot;

scatterplot = function() {
  return d3.json("Data/scatterplot.json", function(weights) {
    var pointcolor, svgscale;
    svgscale = plotframe(weights, {
      chartname: "div#scatterplot",
      xlab: "Week 1 weight (g)",
      ylab: "Week 2 weight (g)",
      height: 700,
      width: 720,
      pad: {
        bottom: 90,
        left: 100,
        top: 0,
        right: 10,
        scale: 0.05
      },
      tickPadding: 8
    });
    pointcolor = function(d) {
      if (d.sex === "FEMALE") {
        return "#58E858"; // green
      } else {
        return "#B10DC9"; // purple
      }
    };
    return svgscale.svg.selectAll("circle", {
      chartname: "#scatterplot"
    }).data(weights).enter().append("circle").attr("cx", function(d) {
      return svgscale.x(d.x);
    }).attr("cy", function(d) {
      return svgscale.y(d.y);
    }).attr("r", 5).attr("fill", pointcolor).on("mouseover", function() {
      return d3.select(this).transition().attr("fill", "black");
    }).on("mouseover.tooltip", function(d, i) {
      return svgscale.svg.append("text").text(i + 1).attr("id", "tooltip").attr("x", svgscale.x(d.x) + 10).attr("y", svgscale.y(d.y)).attr("fill", "black").attr("opacity", 0).style("font-family", "sans-serif").transition().attr("opacity", 1);
    }).on("mouseout", function(d) {
      d3.select(this).transition().duration(500).attr("fill", pointcolor);
      return d3.selectAll("#tooltip").transition().duration(500).attr("opacity", 0).remove();
    });
  });
};

stop_scatterplot = function() {
  return d3.selectAll("div#scatterplot svg").remove();
};
