// Generated by CoffeeScript 1.7.1
var selection_example;

selection_example = function() {
  var circ, colors, h, hilit, i, n, pad, r, rand_pts, rsel, svg, w, _i;
  w = 1280;
  h = 660;
  r = [3, 6];
  rsel = 10;
  pad = r[1] * 2;
  colors = ["#7CF07C", "#6baed6"];
  hilit = "Orchid";
  svg = d3.select("div#selection_example").append("svg").attr("height", h).attr("width", w);
  n = 500;
  rand_pts = [];
  for (i = _i = 0; 0 <= n ? _i < n : _i > n; i = 0 <= n ? ++_i : --_i) {
    rand_pts[i] = {
      x: Math.floor(Math.random() * (w - 2 * pad) + pad),
      y: Math.floor(Math.random() * (h - 2 * pad) + pad),
      size: Math.floor(Math.random() * 2),
      selsize: Math.floor(Math.random() * 2)
    };
  }
  circ = svg.selectAll("empty").data(rand_pts).enter().append("circle").attr("id", function(d, i) {
    return "circ" + i;
  }).attr("cx", function(d) {
    return d.x;
  }).attr("cy", function(d) {
    return d.y;
  }).attr("r", function(d) {
    return r[d.size];
  }).attr("fill", function(d) {
    return colors[d.selsize];
  }).attr("stroke", "none").style("pointer-events", "none");
  return svg.selectAll("empty").data(rand_pts).enter().append("circle").attr("cx", function(d) {
    return d.x;
  }).attr("cy", function(d) {
    return d.y;
  }).attr("r", function(d) {
    if (d.selsize === 1) {
      return rsel;
    }
    return r[d.size];
  }).attr("stroke", "none").attr("fill", hilit).attr("opacity", 0).on("mouseover", function(d, i) {
    d3.select("circle#circ" + i).attr("opacity", 0);
    return d3.select(this).attr("opacity", 1);
  }).on("mouseout", function(d, i) {
    d3.select(this).attr("opacity", 0);
    return d3.select("circle#circ" + i).attr("opacity", 1);
  });
};

selection_example();
